const actions = {
  SET_STATE: 'toolVoucher/SET_STATE',
  HANDLE_STATE: 'toolVoucher/HANDLE_STATE',
  HANDLE_CONTENT: 'toolVoucher/HANDLE_CONTENT',
  GET_DATA_TOOL_VOUCHER_LIST: 'toolVoucher/GET_DATA_TOOL_VOUCHER_LIST',
  GET_DATA_TOOL_VOUCHER_SAVE: 'toolVoucher/GET_DATA_TOOL_VOUCHER_SAVE',
  GET_DATA_TOOL_VOUCHER_UPDATE: 'toolVoucher/GET_DATA_TOOL_VOUCHER_UPDATE',
  GET_DATA_TOOL_VOUCHER_DELETE: 'toolVoucher/GET_DATA_TOOL_VOUCHER_DELETE',
}

export default actions
