const actions = {
  SET_STATE: 'posKasir/SET_STATE',
  HANDLE_STATE: 'posKasir/HANDLE_STATE',
  HANDLE_CONTENT: 'posKasir/HANDLE_CONTENT',
  GET_MST_CUSTOMER_OPTION: 'posKasir/GET_MST_CUSTOMER_OPTION',
  GET_MST_ITEM_OPTION: 'posKasir/GET_MST_ITEM_OPTION',
  GET_TENDER_MEDIA_OPTION: 'posKasir/GET_TENDER_MEDIA_OPTION',
  GET_OUTLET_OPTION: 'posKasir/GET_OUTLET_OPTION',

  HANDLE_OUTLET: 'posKasir/HANDLE_OUTLET',

  HANDLE_SAVE: 'posKasir/HANDLE_SAVE',
}

export default actions
