const actions = {
  SET_STATE: 'membership/SET_STATE',
  GET_DATA_LIST: 'membership/GET_DATA_LIST',
  GET_DATA_DETAIL: 'membership/GET_DATA_DETAIL',

  GET_DATA_PROVINCE_LIST: 'membership/GET_DATA_PROVINCE_LIST',
  GET_DATA_CITY_LIST: 'membership/GET_DATA_CITY_LIST',
  GET_DATA_KECAMATAN_LIST: 'membership/GET_DATA_KECAMATAN_LIST',
  GET_DATA_LAYANAN_MASYARAKAT_LIST: 'membership/GET_DATA_LAYANAN_MASYARAKAT_LIST',

  ADD_KASUS_NARKOBA: 'membership/ADD_KASUS_NARKOBA',
  LIST_KASUS_NARKOBA: 'membership/LIST_KASUS_NARKOBA',

}

export default actions
