const actions = {
  SET_STATE: 'posReport/SET_STATE',
  HANDLE_STATE: 'posReport/HANDLE_STATE',

  GET_BRAND_OPTION: 'posReport/GET_BRAND_OPTION',
  GET_OUTLET_OPTION: 'posReport/GET_OUTLET_OPTION',
  GET_LOCATION_OPTION: 'posReport/GET_LOCATION_OPTION',
  GET_GROUP_OPTION: 'posReport/GET_GROUP_OPTION',
  GET_CATEGORY_OPTION: 'posReport/GET_CATEGORY_OPTION',
}

export default actions
