import endpoint from './endpoint'

const API_MASTER=  "https://jktbersinar.herokuapp.com/"
// const API_MASTER = process.env.REACT_APP_API
const API_MASTER_REPORT = process.env.REACT_APP_API_MASTER_REPORT

const Config = {
  BUILD_FOR: 'CENTRAL',
  BUILD_VERSION: '0.3.0',
  APPSCHEMA: "KIDZOOONA",

  API_LOGIN: API_MASTER + endpoint.EP_LOGIN,
  API_FORGOT: API_MASTER + endpoint.EP_FORGOT,
  API_REGISTER: API_MASTER + endpoint.EP_REGISTER,
  API_FORGOT_CHECK_TOKEN: API_MASTER + endpoint.EP_FORGOT_CHECK_TOKEN,
  API_RESET_PASSWORD: API_MASTER + endpoint.EP_RESET_PASSWORD,
  API_MAINMENU: API_MASTER + endpoint.EP_MENUDATA,
  API_OUTLET: API_MASTER + endpoint.EP_OUTLET,
  API_COMPANY: API_MASTER + endpoint.EP_COMPANY,
  API_OUTLET_BY_COMPANY: API_MASTER + endpoint.EP_OUTLET_BY_COMPANY,
  API_CHANGE_COMPANY: API_MASTER + endpoint.EP_CHANGE_COMPANY,
  API_MODULE_MASTER: API_MASTER + endpoint.EP_MODULE_MASTER,
  API_DASHBOARD: API_MASTER + endpoint.EP_DASHBOARD,

  API_PR_MARKET_LIST: API_MASTER + endpoint.EP_PR_MARKET_LIST,
  API_PR_MARKET_DETAIL: API_MASTER + endpoint.EP_PR_MARKET_DETAIL,
  API_PR_MARKET_SAVE: API_MASTER + endpoint.EP_PR_MARKET_SAVE,
  API_PR_MARKET_UPDATE: API_MASTER + endpoint.EP_PR_MARKET_UPDATE,
  API_PR_MARKET_DELETE: API_MASTER + endpoint.EP_PR_MARKET_DELETE,

  API_PR_REQUEST_LIST: API_MASTER + endpoint.EP_PR_REQUEST_LIST,
  API_PR_REQUEST_DETAIL: API_MASTER + endpoint.EP_PR_REQUEST_DETAIL,
  API_PR_REQUEST_SAVE: API_MASTER + endpoint.EP_PR_REQUEST_SAVE,
  API_PR_REQUEST_UPDATE: API_MASTER + endpoint.EP_PR_REQUEST_UPDATE,
  API_PR_REQUEST_DELETE: API_MASTER + endpoint.EP_PR_REQUEST_DELETE,
  API_PR_REQUEST_APPROVE_ONE: API_MASTER + endpoint.EP_PR_REQUEST_APPROVE_ONE,
  API_PR_REQUEST_APPROVE_TWO: API_MASTER + endpoint.EP_PR_REQUEST_APPROVE_TWO,
  API_PR_REQUEST_APPROVE_THREE: API_MASTER + endpoint.EP_PR_REQUEST_APPROVE_THREE,
  API_PR_REQUEST_CANCEL: API_MASTER + endpoint.EP_PR_REQUEST_CANCEL,
  API_PR_REQUEST_PENDING: API_MASTER + endpoint.EP_PR_REQUEST_PENDING,
  API_PR_REQUEST_PDF: API_MASTER + endpoint.EP_PR_REQUEST_PDF,
  API_PR_REQUEST_IMPORT: API_MASTER + endpoint.EP_PR_REQUEST_IMPORT,

  API_PR_MANAGE_ORDER_LIST: API_MASTER + endpoint.EP_PR_MANAGE_ORDER_LIST,
  API_PR_MANAGE_ORDER_DETAIL: API_MASTER + endpoint.EP_PR_MANAGE_ORDER_DETAIL,
  API_PR_MANAGE_ORDER_UPDATE: API_MASTER + endpoint.EP_PR_MANAGE_ORDER_UPDATE,
  API_PR_MANAGE_ORDER_PURCHASE_APPROVE: API_MASTER + endpoint.EP_PR_MANAGE_ORDER_PURCHASE_APPROVE,
  API_PR_MANAGE_ORDER_PURCHASE_UNAPPROVE:
    API_MASTER + endpoint.EP_PR_MANAGE_ORDER_PURCHASE_UNAPPROVE,
  API_PR_MANAGE_ORDER_COST_APPROVE: API_MASTER + endpoint.EP_PR_MANAGE_ORDER_COST_APPROVE,
  API_PR_MANAGE_ORDER_COST_UNAPPROVE: API_MASTER + endpoint.EP_PR_MANAGE_ORDER_COST_UNAPPROVE,
  API_PR_MANAGE_ORDER_FINANCE_APPROVE: API_MASTER + endpoint.EP_PR_MANAGE_ORDER_FINANCE_APPROVE,
  API_PR_MANAGE_ORDER_FINANCE_UNAPPROVE: API_MASTER + endpoint.EP_PR_MANAGE_ORDER_FINANCE_UNAPPROVE,
  API_PR_MANAGE_ORDER_REQUEST_CREATE_PO: API_MASTER + endpoint.EP_PR_MANAGE_ORDER_CREATE_PO,

  API_PR_PURCHASE_ORDER_LIST: API_MASTER + endpoint.EP_PR_PURCHASE_ORDER_LIST,
  API_PR_PURCHASE_ORDER_OTHER_OPTION: API_MASTER + endpoint.EP_PR_PURCHASE_ORDER_OTHER_OPTION,
  API_PR_PURCHASE_ORDER_OTHER_OPTION_DETAIL:
    API_MASTER + endpoint.EP_PR_PURCHASE_ORDER_OTHER_OPTION_DETAIL,
  API_PR_PURCHASE_ORDER_DETAIL: API_MASTER + endpoint.EP_PR_PURCHASE_ORDER_DETAIL,
  API_PR_PURCHASE_ORDER_SAVE: API_MASTER + endpoint.EP_PR_PURCHASE_ORDER_SAVE,
  API_PR_PURCHASE_ORDER_UPDATE: API_MASTER + endpoint.EP_PR_PURCHASE_ORDER_UPDATE,
  API_PR_PURCHASE_ORDER_DELETE: API_MASTER + endpoint.EP_PR_PURCHASE_ORDER_DELETE,
  API_PR_PURCHASE_ORDER_IMPORT: API_MASTER + endpoint.EP_PR_PURCHASE_ORDER_IMPORT,

  API_PR_PRICE_QUOTE_LIST: API_MASTER + endpoint.EP_PR_PRICE_QUOTE_LIST,
  API_PR_PRICE_QUOTE_DETAIL: API_MASTER + endpoint.EP_PR_PRICE_QUOTE_DETAIL,
  API_PR_PRICE_QUOTE_UPDATE: API_MASTER + endpoint.EP_PR_PRICE_QUOTE_UPDATE,

  API_PR_RETURN_LIST: API_MASTER + endpoint.EP_PR_RETURN_LIST,
  API_PR_RETURN_DETAIL: API_MASTER + endpoint.EP_PR_RETURN_DETAIL,
  API_PR_RETURN_SAVE: API_MASTER + endpoint.EP_PR_RETURN_SAVE,
  API_PR_RETURN_UPDATE: API_MASTER + endpoint.EP_PR_RETURN_UPDATE,
  API_PR_RETURN_APPROVE: API_MASTER + endpoint.EP_PR_RETURN_APPROVE,
  API_PR_RETURN_UNAPPROVE: API_MASTER + endpoint.EP_PR_RETURN_UNAPPROVE,

  API_PR_RECEIVING_LIST: API_MASTER + endpoint.EP_PR_RECEIVING_LIST,
  API_PR_RECEIVING_DETAIL: API_MASTER + endpoint.EP_PR_RECEIVING_DETAIL,
  API_PR_RECEIVING_SAVE: API_MASTER + endpoint.EP_PR_RECEIVING_SAVE,
  API_PR_RECEIVING_UPDATE: API_MASTER + endpoint.EP_PR_RECEIVING_UPDATE,
  API_PR_RECEIVING_APPROVE: API_MASTER + endpoint.EP_PR_RECEIVING_APPROVE,
  API_PR_RECEIVING_UNAPPROVE: API_MASTER + endpoint.EP_PR_RECEIVING_UNAPPROVE,
  API_PR_RECEIVING_CANCEL: API_MASTER + endpoint.EP_PR_RECEIVING_CANCEL,
  API_PR_RECEIVING_PENDING: API_MASTER + endpoint.EP_PR_RECEIVING_PENDING,
  API_PR_RECEIVING_DELETE: API_MASTER + endpoint.EP_PR_RECEIVING_DELETE,
  API_PR_RECEIVING_PO_LIST: API_MASTER + endpoint.EP_PR_RECEIVING_PO_LIST,
  API_PR_RECEIVING_PO_DETAIL: API_MASTER + endpoint.EP_PR_RECEIVING_PO_DETAIL,
  API_PR_RECEIVING_POST: API_MASTER + endpoint.EP_PR_RECEIVING_POST,

  API_PR_RECEIVING_DO_LIST: API_MASTER + endpoint.EP_PR_RECEIVING_DO_LIST,
  API_PR_RECEIVING_DO_DETAIL: API_MASTER + endpoint.EP_PR_RECEIVING_DO_DETAIL,

  API_PR_GOOD_RECEIVING_LIST: API_MASTER + endpoint.EP_PR_GOOD_RECEIVING_LIST,
  API_PR_GOOD_RECEIVING_DETAIL: API_MASTER + endpoint.EP_PR_GOOD_RECEIVING_DETAIL,
  API_PR_GOOD_RECEIVING_SAVE: API_MASTER + endpoint.EP_PR_GOOD_RECEIVING_SAVE,
  API_PR_GOOD_RECEIVING_UPDATE: API_MASTER + endpoint.EP_PR_GOOD_RECEIVING_UPDATE,
  API_PR_GOOD_RECEIVING_POST: API_MASTER + endpoint.EP_PR_GOOD_RECEIVING_POST,
  API_PR_GOOD_RECEIVING_UNPOST: API_MASTER + endpoint.EP_PR_GOOD_RECEIVING_UNPOST,
  API_PR_GOOD_RECEIVING_CANCEL: API_MASTER + endpoint.EP_PR_GOOD_RECEIVING_CANCEL,

  API_PR_INVOICE_LIST: API_MASTER + endpoint.EP_PR_INVOICE_LIST,
  API_PR_INVOICE_DETAIL: API_MASTER + endpoint.EP_PR_INVOICE_DETAIL,
  API_PR_INVOICE_SAVE: API_MASTER + endpoint.EP_PR_INVOICE_SAVE,
  API_PR_INVOICE_UPDATE: API_MASTER + endpoint.EP_PR_INVOICE_UPDATE,
  API_PR_INVOICE_APPROVE: API_MASTER + endpoint.EP_PR_INVOICE_APPROVE,
  API_PR_INVOICE_UNAPPROVE: API_MASTER + endpoint.EP_PR_INVOICE_UNAPPROVE,
  API_PR_INVOICE_CANCEL: API_MASTER + endpoint.EP_PR_INVOICE_CANCEL,
  API_PR_INVOICE_GOOD_RECEIVING_LIST: API_MASTER + endpoint.EP_PR_INVOICE_GOOD_RECEIVING_LIST,
  API_PR_INVOICE_GOOD_RECEIVING_DETAIL: API_MASTER + endpoint.EP_PR_INVOICE_GOOD_RECEIVING_DETAIL,

  API_PR_DIRECT_INVOICE_LIST: API_MASTER + endpoint.EP_PR_DIRECT_INVOICE_LIST,
  API_PR_DIRECT_INVOICE_DETAIL: API_MASTER + endpoint.EP_PR_DIRECT_INVOICE_DETAIL,
  API_PR_DIRECT_INVOICE_SAVE: API_MASTER + endpoint.EP_PR_DIRECT_INVOICE_SAVE,
  API_PR_DIRECT_INVOICE_UPDATE: API_MASTER + endpoint.EP_PR_DIRECT_INVOICE_UPDATE,
  API_PR_DIRECT_INVOICE_APPROVE: API_MASTER + endpoint.EP_PR_DIRECT_INVOICE_APPROVE,
  API_PR_DIRECT_INVOICE_UNAPPROVE: API_MASTER + endpoint.EP_PR_DIRECT_INVOICE_UNAPPROVE,
  API_PR_DIRECT_INVOICE_DELETE: API_MASTER + endpoint.EP_PR_DIRECT_INVOICE_DELETE,

  API_PR_REPORT_RECEIVING: API_MASTER + endpoint.EP_PR_REPORT_RECEIVING,

  API_MST_BRAND_LIST: API_MASTER + endpoint.EP_MST_BRAND_LIST,
  API_MST_BRAND_LIST_MULTICOMPANY: API_MASTER + endpoint.EP_MST_BRAND_LIST_MULTICOMPANY,
  API_MST_BRAND_SAVE: API_MASTER + endpoint.EP_MST_BRAND_SAVE,
  API_MST_BRAND_UPDATE: API_MASTER + endpoint.EP_MST_BRAND_UPDATE,
  API_MST_BRAND_DELETE: API_MASTER + endpoint.EP_MST_BRAND_DELETE,

  API_MST_BANK_CODE_LIST: API_MASTER + endpoint.EP_MST_BANK_CODE_LIST,
  API_MST_BANK_CODE_SAVE: API_MASTER + endpoint.EP_MST_BANK_CODE_SAVE,
  API_MST_BANK_CODE_UPDATE: API_MASTER + endpoint.EP_MST_BANK_CODE_UPDATE,
  API_MST_BANK_CODE_DELETE: API_MASTER + endpoint.EP_MST_BANK_CODE_DELETE,

  API_MST_ADJUSTMENT_REASON_LIST: API_MASTER + endpoint.EP_MST_ADJUSTMENT_REASON_LIST,
  API_MST_ADJUSTMENT_REASON_SAVE: API_MASTER + endpoint.EP_MST_ADJUSTMENT_REASON_SAVE,
  API_MST_ADJUSTMENT_REASON_UPDATE: API_MASTER + endpoint.EP_MST_ADJUSTMENT_REASON_UPDATE,
  API_MST_ADJUSTMENT_REASON_DELETE: API_MASTER + endpoint.EP_MST_ADJUSTMENT_REASON_DELETE,

  API_MST_COMPANY_LIST: API_MASTER + endpoint.EP_MST_COMPANY_LIST,
  API_MST_COMPANY_DETAIL: API_MASTER + endpoint.EP_MST_COMPANY_DETAIL,
  API_MST_COMPANY_SAVE: API_MASTER + endpoint.EP_MST_COMPANY_SAVE,
  API_MST_COMPANY_UPDATE: API_MASTER + endpoint.EP_MST_COMPANY_UPDATE,
  API_MST_COMPANY_DELETE: API_MASTER + endpoint.EP_MST_COMPANY_DELETE,

  API_MST_UNIT_MEASURE_LIST: API_MASTER + endpoint.EP_MST_UNIT_MEASURE_LIST,
  API_MST_UNIT_MEASURE_SAVE: API_MASTER + endpoint.EP_MST_UNIT_MEASURE_SAVE,
  API_MST_UNIT_MEASURE_UPDATE: API_MASTER + endpoint.EP_MST_UNIT_MEASURE_UPDATE,
  API_MST_UNIT_MEASURE_DELETE: API_MASTER + endpoint.EP_MST_UNIT_MEASURE_DELETE,

  API_MST_SUPPLIER_LIST: API_MASTER + endpoint.EP_MST_SUPPLIER_LIST,
  API_MST_SUPPLIER_DETAIL: API_MASTER + endpoint.EP_MST_SUPPLIER_DETAIL,
  API_MST_SUPPLIER_SAVE: API_MASTER + endpoint.EP_MST_SUPPLIER_SAVE,
  API_MST_SUPPLIER_UPDATE: API_MASTER + endpoint.EP_MST_SUPPLIER_UPDATE,
  API_MST_SUPPLIER_DELETE: API_MASTER + endpoint.EP_MST_SUPPLIER_DELETE,

  API_MST_ROLE_LIST: API_MASTER + endpoint.EP_MST_ROLE_LIST,
  API_MST_ROLE_DETAIL: API_MASTER + endpoint.EP_MST_ROLE_DETAIL,
  API_MST_ROLE_SAVE: API_MASTER + endpoint.EP_MST_ROLE_SAVE,
  API_MST_ROLE_UPDATE: API_MASTER + endpoint.EP_MST_ROLE_UPDATE,
  API_MST_ROLE_DELETE: API_MASTER + endpoint.EP_MST_ROLE_DELETE,

  API_MST_USER_LIST: API_MASTER + endpoint.EP_MST_USER_LIST,
  API_MST_USER_DETAIL: API_MASTER + endpoint.EP_MST_USER_DETAIL,
  API_MST_USER_SAVE: API_MASTER + endpoint.EP_MST_USER_SAVE,
  API_MST_USER_UPDATE: API_MASTER + endpoint.EP_MST_USER_UPDATE,
  API_MST_USER_MODULE_LIST: API_MASTER + endpoint.EP_MST_USER_MODULE_LIST,
  API_MST_USER_SUB_MODULE_LIST: API_MASTER + endpoint.EP_MST_USER_SUB_MODULE_LIST,

  API_MST_SHIPMENT_METHOD_LIST: API_MASTER + endpoint.EP_MST_SHIPMENT_METHOD_LIST,

  API_MST_CURRENCY_LIST: API_MASTER + endpoint.EP_MST_CURRENCY_LIST,
  API_MST_CURRENCY_SAVE: API_MASTER + endpoint.EP_MST_CURRENCY_SAVE,
  API_MST_CURRENCY_UPDATE: API_MASTER + endpoint.EP_MST_CURRENCY_UPDATE,
  API_MST_CURRENCY_DELETE: API_MASTER + endpoint.EP_MST_CURRENCY_DELETE,

  API_MST_CATEGORY_ITEM_LIST: API_MASTER + endpoint.EP_MST_CATEGORY_ITEM_LIST,
  API_MST_CATEGORY_ITEM_SAVE: API_MASTER + endpoint.EP_MST_CATEGORY_ITEM_SAVE,
  API_MST_CATEGORY_ITEM_UPDATE: API_MASTER + endpoint.EP_MST_CATEGORY_ITEM_UPDATE,
  API_MST_CATEGORY_ITEM_DELETE: API_MASTER + endpoint.EP_MST_CATEGORY_ITEM_DELETE,

  API_MST_GROUP_ITEM_LIST: API_MASTER + endpoint.EP_MST_GROUP_ITEM_LIST,
  API_MST_GROUP_ITEM_SAVE: API_MASTER + endpoint.EP_MST_GROUP_ITEM_SAVE,
  API_MST_GROUP_ITEM_UPDATE: API_MASTER + endpoint.EP_MST_GROUP_ITEM_UPDATE,
  API_MST_GROUP_ITEM_DELETE: API_MASTER + endpoint.EP_MST_GROUP_ITEM_DELETE,

  API_MST_DEPARTMENT_LIST: API_MASTER + endpoint.EP_MST_DEPARTMENT_LIST,

  API_MST_CHART_ACCOUNT_LIST: API_MASTER + endpoint.EP_MST_CHART_ACCOUNT_LIST,
  API_MST_CHART_ACCOUNT_SAVE: API_MASTER + endpoint.EP_MST_CHART_ACCOUNT_SAVE,
  API_MST_CHART_ACCOUNT_UPDATE: API_MASTER + endpoint.EP_MST_CHART_ACCOUNT_UPDATE,
  API_MST_CHART_ACCOUNT_DELETE: API_MASTER + endpoint.EP_MST_CHART_ACCOUNT_DELETE,
  API_MST_CHART_ACCOUNT_CLASS_LIST: API_MASTER + endpoint.EP_MST_CHART_ACCOUNT_CLASS_LIST,

  API_MST_TAX_TABLE_LIST: API_MASTER + endpoint.EP_MST_TAX_TABLE_LIST,
  API_MST_TAX_TABLE_SAVE: API_MASTER + endpoint.EP_MST_TAX_TABLE_SAVE,
  API_MST_TAX_TABLE_UPDATE: API_MASTER + endpoint.EP_MST_TAX_TABLE_UPDATE,
  API_MST_TAX_TABLE_DELETE: API_MASTER + endpoint.EP_MST_TAX_TABLE_DELETE,

  API_MST_OUTLET_LIST: API_MASTER + endpoint.EP_MST_OUTLET_LIST,
  API_MST_FB_OUTLET_LIST: API_MASTER + endpoint.EP_POS_MENU_OUTLET_LIST,
  API_MST_OUTLET_LIST_MULTIBRAND: API_MASTER + endpoint.EP_MST_OUTLET_LIST_MULTIBRAND,
  API_MST_OUTLET_BRAND: API_MASTER + endpoint.EP_MST_OUTLET_BRAND,
  API_MST_OUTLET_DETAIL: API_MASTER + endpoint.EP_MST_OUTLET_DETAIL,
  API_MST_OUTLET_SAVE: API_MASTER + endpoint.EP_MST_OUTLET_SAVE,
  API_MST_OUTLET_UPDATE: API_MASTER + endpoint.EP_MST_OUTLET_UPDATE,
  API_MST_OUTLET_DELETE: API_MASTER + endpoint.EP_MST_OUTLET_DELETE,

  API_MST_ITEMS_LIST: API_MASTER + endpoint.EP_MST_ITEMS_LIST,
  API_MST_ITEMS_DETAIL: API_MASTER + endpoint.EP_MST_ITEMS_DETAIL,
  API_MST_ITEMS_SAVE: API_MASTER + endpoint.EP_MST_ITEMS_SAVE,
  API_MST_ITEMS_UPDATE: API_MASTER + endpoint.EP_MST_ITEMS_UPDATE,
  API_MST_ITEMS_DELETE: API_MASTER + endpoint.EP_MST_ITEMS_DELETE,
  API_MST_ITEMS_SUPPLIER_LIST: API_MASTER + endpoint.EP_MST_ITEMS_SUPPLIER_LIST,
  API_MST_ITEMS_LOCATION_LIST: API_MASTER + endpoint.EP_MST_ITEMS_LOCATION_LIST,
  API_MST_ITEMS_LOCATION_FIX_LIST: API_MASTER + endpoint.EP_MST_ITEMS_LOCATION_FIX_LIST,
  API_MST_ITEMS_RECIPE: API_MASTER + endpoint.EP_MST_ITEMS_RECIPE,
  API_MST_ITEMS_PRODUCTION: API_MASTER + endpoint.EP_MST_ITEMS_PRODUCTION,

  API_MST_CUSTOMER_LIST: API_MASTER + endpoint.EP_MST_CUSTOMER_LIST,
  API_MST_CUSTOMER_DETAIL: API_MASTER + endpoint.EP_MST_CUSTOMER_DETAIL,
  API_MST_CUSTOMER_SAVE: API_MASTER + endpoint.EP_MST_CUSTOMER_SAVE,
  API_MST_CUSTOMER_UPDATE: API_MASTER + endpoint.EP_MST_CUSTOMER_UPDATE,
  API_MST_CUSTOMER_DELETE: API_MASTER + endpoint.EP_MST_CUSTOMER_DELETE,

  API_MST_LOCATION_LIST: API_MASTER + endpoint.EP_MST_LOCATION_LIST,
  API_MST_LOCATION_LIST_MULTIOUTLET: API_MASTER + endpoint.EP_MST_LOCATION_LIST_MULTIOUTLET,
  API_MST_LOCATION_SAVE: API_MASTER + endpoint.EP_MST_LOCATION_SAVE,
  API_MST_LOCATION_UPDATE: API_MASTER + endpoint.EP_MST_LOCATION_UPDATE,

  API_MST_WAREHOUSE_LIST: API_MASTER + endpoint.EP_MST_WAREHOUSE_LIST,

  API_MST_CHARGE_LIST: API_MASTER + endpoint.EP_MST_CHARGE_LIST,

  API_MST_TERM_PAYMENT_LIST: API_MASTER + endpoint.EP_MST_TERM_PAYMENT_LIST,
  API_MST_TERM_PAYMENT_SAVE: API_MASTER + endpoint.EP_MST_TERM_PAYMENT_SAVE,
  API_MST_TERM_PAYMENT_UPDATE: API_MASTER + endpoint.EP_MST_TERM_PAYMENT_UPDATE,
  API_MST_TERM_PAYMENT_DELETE: API_MASTER + endpoint.EP_MST_TERM_PAYMENT_DELETE,

  API_MST_POSTING_GROUP_LIST: API_MASTER + endpoint.EP_MST_POSTING_GROUP_LIST,
  API_MST_POSTING_GROUP_SAVE: API_MASTER + endpoint.EP_MST_POSTING_GROUP_SAVE,
  API_MST_POSTING_GROUP_UPDATE: API_MASTER + endpoint.EP_MST_POSTING_GROUP_UPDATE,
  API_MST_POSTING_GROUP_DELETE: API_MASTER + endpoint.EP_MST_POSTING_GROUP_DELETE,
  API_MST_SUPPLIER_POSTING_GROUP_LIST: API_MASTER + endpoint.EP_MST_SUPPLIER_POSTING_GROUP_LIST,
  API_MST_SUPPLIER_POSTING_GROUP_SAVE: API_MASTER + endpoint.EP_MST_SUPPLIER_POSTING_GROUP_SAVE,
  API_MST_SUPPLIER_POSTING_GROUP_UPDATE: API_MASTER + endpoint.EP_MST_SUPPLIER_POSTING_GROUP_UPDATE,
  API_MST_SUPPLIER_POSTING_GROUP_DELETE: API_MASTER + endpoint.EP_MST_SUPPLIER_POSTING_GROUP_DELETE,

  API_MST_SALES_PERSON_LIST: API_MASTER + endpoint.EP_MST_SALES_PERSON_LIST,
  API_MST_SALES_PERSON_SAVE: API_MASTER + endpoint.EP_MST_SALES_PERSON_SAVE,
  API_MST_SALES_PERSON_UPDATE: API_MASTER + endpoint.EP_MST_SALES_PERSON_UPDATE,

  API_MST_COUNTRY_LIST: API_MASTER + endpoint.EP_MST_COUNTRY_LIST,
  API_MST_COUNTRY_SAVE: API_MASTER + endpoint.EP_MST_COUNTRY_SAVE,
  API_MST_COUNTRY_UPDATE: API_MASTER + endpoint.EP_MST_COUNTRY_UPDATE,

  API_INV_ADJUSTMENT_IN_LIST: API_MASTER + endpoint.EP_INV_ADJUSTMENT_IN_LIST,
  API_INV_ADJUSTMENT_IN_DETAIL: API_MASTER + endpoint.EP_INV_ADJUSTMENT_IN_DETAIL,
  API_INV_ADJUSTMENT_IN_SAVE: API_MASTER + endpoint.EP_INV_ADJUSTMENT_IN_SAVE,
  API_INV_ADJUSTMENT_IN_UPDATE: API_MASTER + endpoint.EP_INV_ADJUSTMENT_IN_UPDATE,
  API_INV_ADJUSTMENT_IN_DELETE: API_MASTER + endpoint.EP_INV_ADJUSTMENT_IN_DELETE,
  API_INV_ADJUSTMENT_IN_POSTING: API_MASTER + endpoint.EP_INV_ADJUSTMENT_IN_POSTING,
  API_INV_ADJUSTMENT_IN_UNPOSTING: API_MASTER + endpoint.EP_INV_ADJUSTMENT_IN_UNPOSTING,

  API_INV_ADJUSTMENT_OUT_LIST: API_MASTER + endpoint.EP_INV_ADJUSTMENT_OUT_LIST,
  API_INV_ADJUSTMENT_OUT_DETAIL: API_MASTER + endpoint.EP_INV_ADJUSTMENT_OUT_DETAIL,
  API_INV_ADJUSTMENT_OUT_SAVE: API_MASTER + endpoint.EP_INV_ADJUSTMENT_OUT_SAVE,
  API_INV_ADJUSTMENT_OUT_UPDATE: API_MASTER + endpoint.EP_INV_ADJUSTMENT_OUT_UPDATE,
  API_INV_ADJUSTMENT_OUT_DELETE: API_MASTER + endpoint.EP_INV_ADJUSTMENT_OUT_DELETE,
  API_INV_ADJUSTMENT_OUT_POSTING: API_MASTER + endpoint.EP_INV_ADJUSTMENT_OUT_POSTING,
  API_INV_ADJUSTMENT_OUT_UNPOSTING: API_MASTER + endpoint.EP_INV_ADJUSTMENT_OUT_UNPOSTING,

  API_INV_OUTLET_REQUEST_LIST: API_MASTER + endpoint.EP_INV_OUTLET_REQUEST_LIST,
  API_INV_OUTLET_REQUEST_DETAIL: API_MASTER + endpoint.EP_INV_OUTLET_REQUEST_DETAIL,
  API_INV_OUTLET_REQUEST_SAVE: API_MASTER + endpoint.EP_INV_OUTLET_REQUEST_SAVE,
  API_INV_OUTLET_REQUEST_UPDATE: API_MASTER + endpoint.EP_INV_OUTLET_REQUEST_UPDATE,
  API_INV_OUTLET_REQUEST_DELETE: API_MASTER + endpoint.EP_INV_OUTLET_REQUEST_DELETE,
  API_INV_OUTLET_REQUEST_APPROVE: API_MASTER + endpoint.EP_INV_OUTLET_REQUEST_APPROVE,
  API_INV_OUTLET_REQUEST_UNAPPROVE: API_MASTER + endpoint.EP_INV_OUTLET_REQUEST_UNAPPROVE,
  API_INV_OUTLET_REQUEST_CANCEL: API_MASTER + endpoint.EP_INV_OUTLET_REQUEST_CANCEL,

  API_INV_DELIVERY_OUTLET_REQUEST_LIST: API_MASTER + endpoint.EP_INV_DELIVERY_OUTLET_REQUEST_LIST,
  API_INV_DELIVERY_OUTLET_REQUEST_DETAIL:
    API_MASTER + endpoint.EP_INV_DELIVERY_OUTLET_REQUEST_DETAIL,
  API_INV_DELIVERY_OUTLET_REQUEST_DELETE:
    API_MASTER + endpoint.EP_INV_DELIVERY_OUTLET_REQUEST_DELETE,
  API_INV_DELIVERY_OUTLET_REQUEST_UPDATE:
    API_MASTER + endpoint.EP_INV_DELIVERY_OUTLET_REQUEST_UPDATE,
  API_INV_DELIVERY_OUTLET_REQUEST_POSTING:
    API_MASTER + endpoint.EP_INV_DELIVERY_OUTLET_REQUEST_POSTING,
  API_INV_DELIVERY_OUTLET_REQUEST_UNPOSTING:
    API_MASTER + endpoint.EP_INV_DELIVERY_OUTLET_REQUEST_UNPOSTING,

  API_INV_OUTLET_REQUEST_OVERVIEW_LIST: API_MASTER + endpoint.EP_INV_OUTLET_REQUEST_OVERVIEW_LIST,
  API_INV_OUTLET_REQUEST_OVERVIEW_DETAIL:
    API_MASTER + endpoint.EP_INV_OUTLET_REQUEST_OVERVIEW_DETAIL,
  API_INV_OUTLET_REQUEST_OVERVIEW_CHECK_STOCK:
    API_MASTER + endpoint.EP_INV_OUTLET_REQUEST_OVERVIEW_CHECK_STOCK,
  API_INV_OUTLET_REQUEST_OVERVIEW_CREATE_DOR:
    API_MASTER + endpoint.EP_INV_OUTLET_REQUEST_OVERVIEW_CREATE_DOR,
  API_INV_OUTLET_REQUEST_OVERVIEW_CREATE_EXCEL:
    API_MASTER + endpoint.EP_INV_OUTLET_REQUEST_OVERVIEW_CREATE_EXCEL,

  API_INV_TRANSFER_OUT_LIST: API_MASTER + endpoint.EP_INV_TRANSFER_OUT_LIST,
  API_INV_TRANSFER_OUT_DETAIL: API_MASTER + endpoint.EP_INV_TRANSFER_OUT_DETAIL,
  API_INV_TRANSFER_OUT_SAVE: API_MASTER + endpoint.EP_INV_TRANSFER_OUT_SAVE,
  API_INV_TRANSFER_OUT_UPDATE: API_MASTER + endpoint.EP_INV_TRANSFER_OUT_UPDATE,
  API_INV_TRANSFER_OUT_DELETE: API_MASTER + endpoint.EP_INV_TRANSFER_OUT_DELETE,
  API_INV_TRANSFER_OUT_POST: API_MASTER + endpoint.EP_INV_TRANSFER_OUT_POST,
  API_INV_TRANSFER_OUT_UNPOST: API_MASTER + endpoint.EP_INV_TRANSFER_OUT_UNPOST,

  API_INV_WAREHOUSE_MUTATION_LIST: API_MASTER + endpoint.EP_INV_WAREHOUSE_MUTATION_LIST,
  API_INV_WAREHOUSE_MUTATION_DETAIL: API_MASTER + endpoint.EP_INV_WAREHOUSE_MUTATION_DETAIL,
  API_INV_WAREHOUSE_MUTATION_SAVE: API_MASTER + endpoint.EP_INV_WAREHOUSE_MUTATION_SAVE,
  API_INV_WAREHOUSE_MUTATION_UPDATE: API_MASTER + endpoint.EP_INV_WAREHOUSE_MUTATION_UPDATE,
  API_INV_WAREHOUSE_MUTATION_DELETE: API_MASTER + endpoint.EP_INV_WAREHOUSE_MUTATION_DELETE,
  API_INV_WAREHOUSE_MUTATION_POSTING: API_MASTER + endpoint.EP_INV_WAREHOUSE_MUTATION_POSTING,
  API_INV_WAREHOUSE_MUTATION_UNPOSTING: API_MASTER + endpoint.EP_INV_WAREHOUSE_MUTATION_UNPOSTING,

  API_INV_STOCK_OPNAME_LIST: API_MASTER + endpoint.EP_INV_STOCK_OPNAME_LIST,
  API_INV_STOCK_OPNAME_DETAIL: API_MASTER + endpoint.EP_INV_STOCK_OPNAME_DETAIL,
  API_INV_STOCK_OPNAME_SAVE: API_MASTER + endpoint.EP_INV_STOCK_OPNAME_SAVE,
  API_INV_STOCK_OPNAME_UPDATE: API_MASTER + endpoint.EP_INV_STOCK_OPNAME_UPDATE,
  API_INV_STOCK_OPNAME_DELETE: API_MASTER + endpoint.EP_INV_STOCK_OPNAME_DELETE,
  API_INV_STOCK_OPNAME_APPROVE: API_MASTER + endpoint.EP_INV_STOCK_OPNAME_APPROVE,
  API_INV_STOCK_OPNAME_UNAPPROVE: API_MASTER + endpoint.EP_INV_STOCK_OPNAME_UNAPPROVE,
  API_INV_STOCK_OPNAME_IMPORT: API_MASTER + endpoint.EP_INV_STOCK_OPNAME_IMPORT,
  API_INV_STOCK_OPNAME_LOADDATA: API_MASTER + endpoint.EP_INV_STOCK_OPNAME_LOADDATA,

  API_INV_STOCK_CARD: API_MASTER + endpoint.EP_INV_STOCK_CARD,
  API_INV_STOCK_DETAIL_QUANTITY: API_MASTER + endpoint.EP_INV_STOCK_DETAIL_QUANTITY,
  API_INV_STOCK_DETAIL_PRICE: API_MASTER + endpoint.EP_INV_STOCK_DETAIL_PRICE,
  API_INV_STOCK_DETAIL_CONSUME: API_MASTER + endpoint.EP_INV_STOCK_DETAIL_CONSUME,
  API_INV_STOCK_DETAIL_RECAP: API_MASTER + endpoint.EP_INV_STOCK_DETAIL_RECAP,

  API_PRD_RECIPE_LIST: API_MASTER + endpoint.EP_PRD_RECIPE_LIST,
  API_PRD_RECIPE_DETAIL: API_MASTER + endpoint.EP_PRD_RECIPE_DETAIL,
  API_PRD_RECIPE_SAVE: API_MASTER + endpoint.EP_PRD_RECIPE_SAVE,
  API_PRD_RECIPE_UPDATE: API_MASTER + endpoint.EP_PRD_RECIPE_UPDATE,
  API_PRD_RECIPE_DELETE: API_MASTER + endpoint.EP_PRD_RECIPE_DELETE,

  API_PRD_CONVERT_ITEMS_LIST: API_MASTER + endpoint.EP_PRD_CONVERT_ITEMS_LIST,
  API_PRD_CONVERT_ITEMS_DETAIL: API_MASTER + endpoint.EP_PRD_CONVERT_ITEMS_DETAIL,
  API_PRD_CONVERT_ITEMS_SAVE: API_MASTER + endpoint.EP_PRD_CONVERT_ITEMS_SAVE,
  API_PRD_CONVERT_ITEMS_UPDATE: API_MASTER + endpoint.EP_PRD_CONVERT_ITEMS_UPDATE,
  API_PRD_CONVERT_ITEMS_DELETE: API_MASTER + endpoint.EP_PRD_CONVERT_ITEMS_DELETE,
  API_PRD_CONVERT_ITEMS_APPROVE: API_MASTER + endpoint.EP_PRD_CONVERT_ITEMS_APPROVE,
  API_PRD_CONVERT_ITEMS_UNAPPROVE: API_MASTER + endpoint.EP_PRD_CONVERT_ITEMS_UNAPPROVE,

  API_PRD_PRODUCTION_LIST: API_MASTER + endpoint.EP_PRD_PRODUCTION_LIST,
  API_PRD_PRODUCTION_DETAIL: API_MASTER + endpoint.EP_PRD_PRODUCTION_DETAIL,
  API_PRD_PRODUCTION_SAVE: API_MASTER + endpoint.EP_PRD_PRODUCTION_SAVE,
  API_PRD_PRODUCTION_UPDATE: API_MASTER + endpoint.EP_PRD_PRODUCTION_UPDATE,
  API_PRD_PRODUCTION_DELETE: API_MASTER + endpoint.EP_PRD_PRODUCTION_DELETE,
  API_PRD_PRODUCTION_APPROVE: API_MASTER + endpoint.EP_PRD_PRODUCTION_APPROVE,
  API_PRD_PRODUCTION_UNAPPROVE: API_MASTER + endpoint.EP_PRD_PRODUCTION_UNAPPROVE,

  API_SLS_SALES_ORDER_LIST: API_MASTER + endpoint.EP_SLS_SALES_ORDER_LIST,
  API_SLS_SALES_ORDER_DETAIL: API_MASTER + endpoint.EP_SLS_SALES_ORDER_DETAIL,
  API_SLS_SALES_ORDER_SAVE: API_MASTER + endpoint.EP_SLS_SALES_ORDER_SAVE,
  API_SLS_SALES_ORDER_UPDATE: API_MASTER + endpoint.EP_SLS_SALES_ORDER_UPDATE,
  API_SLS_SALES_ORDER_DELETE: API_MASTER + endpoint.EP_SLS_SALES_ORDER_DELETE,

  API_SLS_SALES_INVOICE_LIST: API_MASTER + endpoint.EP_SLS_SALES_INVOICE_LIST,
  API_SLS_SALES_INVOICE_DETAIL: API_MASTER + endpoint.EP_SLS_SALES_INVOICE_DETAIL,
  API_SLS_SALES_INVOICE_SAVE: API_MASTER + endpoint.EP_SLS_SALES_INVOICE_SAVE,
  API_SLS_SALES_INVOICE_GENERATE: API_MASTER + endpoint.EP_SLS_SALES_INVOICE_GENERATE,
  API_SLS_SALES_INVOICE_UPDATE: API_MASTER + endpoint.EP_SLS_SALES_INVOICE_UPDATE,
  API_SLS_SALES_INVOICE_DELETE: API_MASTER + endpoint.EP_SLS_SALES_INVOICE_DELETE,
  API_SLS_SALES_INVOICE_APPROVE: API_MASTER + endpoint.EP_SLS_SALES_INVOICE_APPROVE,
  API_SLS_SALES_INVOICE_UNAPPROVE: API_MASTER + endpoint.EP_SLS_SALES_INVOICE_UNAPPROVE,

  API_SLS_PACKING_LIST_LIST: API_MASTER + endpoint.EP_SLS_PACKING_LIST_LIST,
  API_SLS_PACKING_LIST_DETAIL: API_MASTER + endpoint.EP_SLS_PACKING_LIST_DETAIL,
  API_SLS_PACKING_LIST_SAVE: API_MASTER + endpoint.EP_SLS_PACKING_LIST_SAVE,
  API_SLS_PACKING_LIST_UPDATE: API_MASTER + endpoint.EP_SLS_PACKING_LIST_UPDATE,
  API_SLS_PACKING_LIST_DELETE: API_MASTER + endpoint.EP_SLS_PACKING_LIST_DELETE,

  API_SLS_SALES_RETURN_LIST: API_MASTER + endpoint.EP_SLS_SALES_RETURN_LIST,
  API_SLS_SALES_RETURN_DETAIL: API_MASTER + endpoint.EP_SLS_SALES_RETURN_DETAIL,
  API_SLS_SALES_RETURN_SAVE: API_MASTER + endpoint.EP_SLS_SALES_RETURN_SAVE,
  API_SLS_SALES_RETURN_UPDATE: API_MASTER + endpoint.EP_SLS_SALES_RETURN_UPDATE,
  API_SLS_SALES_RETURN_DELETE: API_MASTER + endpoint.EP_SLS_SALES_RETURN_DELETE,

  API_SLS_DELIVERY_ORDER_LIST: API_MASTER + endpoint.EP_SLS_DELIVERY_ORDER_LIST,
  API_SLS_DELIVERY_ORDER_DETAIL: API_MASTER + endpoint.EP_SLS_DELIVERY_ORDER_DETAIL,
  API_SLS_DELIVERY_ORDER_SAVE: API_MASTER + endpoint.EP_SLS_DELIVERY_ORDER_SAVE,
  API_SLS_DELIVERY_ORDER_UPDATE: API_MASTER + endpoint.EP_SLS_DELIVERY_ORDER_UPDATE,
  API_SLS_DELIVERY_ORDER_APPROVE: API_MASTER + endpoint.EP_SLS_DELIVERY_ORDER_APPROVE,
  API_SLS_DELIVERY_ORDER_UNAPPROVE: API_MASTER + endpoint.EP_SLS_DELIVERY_ORDER_UNAPPROVE,

  API_SLS_SALES_BY_CUST_LIST: API_MASTER + endpoint.EP_SLS_SALES_BY_CUST_LIST,

  API_SLS_PO_OUTLET_LIST: API_MASTER + endpoint.EP_SLS_PO_OUTLET_LIST,
  API_SLS_PO_OUTLET_DETAIL: API_MASTER + endpoint.EP_SLS_PO_OUTLET_DETAIL,

  API_SLS_SALES_BY_ITEM_REPORT_LIST: API_MASTER + endpoint.EP_SLS_SLS_BY_ITEM_REPORT,

  API_FIN_CREDIT_NOTE_LIST: API_MASTER + endpoint.EP_FIN_CREDIT_NOTE_LIST,
  API_FIN_CREDIT_NOTE_DETAIL: API_MASTER + endpoint.EP_FIN_CREDIT_NOTE_DETAIL,
  API_FIN_CREDIT_NOTE_SAVE: API_MASTER + endpoint.EP_FIN_CREDIT_NOTE_SAVE,
  API_FIN_CREDIT_NOTE_UPDATE: API_MASTER + endpoint.EP_FIN_CREDIT_NOTE_UPDATE,
  API_FIN_CREDIT_NOTE_DELETE: API_MASTER + endpoint.EP_FIN_CREDIT_NOTE_DELETE,

  API_FIN_DEBIT_NOTE_LIST: API_MASTER + endpoint.EP_FIN_DEBIT_NOTE_LIST,
  API_FIN_DEBIT_NOTE_DETAIL: API_MASTER + endpoint.EP_FIN_DEBIT_NOTE_DETAIL,
  API_FIN_DEBIT_NOTE_SAVE: API_MASTER + endpoint.EP_FIN_DEBIT_NOTE_SAVE,
  API_FIN_DEBIT_NOTE_UPDATE: API_MASTER + endpoint.EP_FIN_DEBIT_NOTE_UPDATE,
  API_FIN_DEBIT_NOTE_DELETE: API_MASTER + endpoint.EP_FIN_DEBIT_NOTE_DELETE,

  API_FIN_PAYMENT_VOUCHER_LIST: API_MASTER + endpoint.EP_FIN_PAYMENT_VOUCHER_LIST,
  API_FIN_PAYMENT_VOUCHER_DETAIL: API_MASTER + endpoint.EP_FIN_PAYMENT_VOUCHER_DETAIL,
  API_FIN_PAYMENT_VOUCHER_INVOICE: API_MASTER + endpoint.EP_FIN_PAYMENT_VOUCHER_INVOICE,
  API_FIN_PAYMENT_VOUCHER_SAVE: API_MASTER + endpoint.EP_FIN_PAYMENT_VOUCHER_SAVE,
  API_FIN_PAYMENT_VOUCHER_DELETE: API_MASTER + endpoint.EP_FIN_PAYMENT_VOUCHER_DELETE,
  API_FIN_PAYMENT_VOUCHER_UPDATE: API_MASTER + endpoint.EP_FIN_PAYMENT_VOUCHER_UPDATE,
  API_FIN_PAYMENT_VOUCHER_APPROVE: API_MASTER + endpoint.EP_FIN_PAYMENT_VOUCHER_APPROVE,
  API_FIN_PAYMENT_VOUCHER_PREPARE: API_MASTER + endpoint.EP_FIN_PAYMENT_VOUCHER_PREPARE,

  API_FIN_AP_VOUCHER_LIST: API_MASTER + endpoint.EP_FIN_AP_VOUCHER_LIST,

  API_FIN_ISSUED_LIST: API_MASTER + endpoint.EP_FIN_ISSUED_LIST,
  API_FIN_ISSUED_DETAIL: API_MASTER + endpoint.EP_FIN_ISSUED_DETAIL,
  API_FIN_ISSUED_ISSUE: API_MASTER + endpoint.EP_FIN_ISSUED_ISSUE,
  API_FIN_ISSUED_APPROVE: API_MASTER + endpoint.EP_FIN_ISSUED_APPROVE,

  API_FIN_RECONCIALE_LIST: API_MASTER + endpoint.EP_FIN_RECONCIALE_LIST,
  API_FIN_RECONCIALE_DETAIL: API_MASTER + endpoint.EP_FIN_RECONCIALE_DETAIL,
  API_FIN_RECONCIALE_ISSUE: API_MASTER + endpoint.EP_FIN_RECONCIALE_ISSUE,
  API_FIN_RECONCIALE_RECONCILE: API_MASTER + endpoint.EP_FIN_RECONCIALE_RECONCILE,

  API_FIN_BANK_ACCOUNT_LIST: API_MASTER + endpoint.EP_FIN_BANK_ACCOUNT_LIST,
  API_FIN_BANK_ACCOUNT_DETAIL: API_MASTER + endpoint.EP_FIN_BANK_ACCOUNT_DETAIL,
  API_FIN_BANK_ACCOUNT_SAVE: API_MASTER + endpoint.EP_FIN_BANK_ACCOUNT_SAVE,
  API_FIN_BANK_ACCOUNT_UPDATE: API_MASTER + endpoint.EP_FIN_BANK_ACCOUNT_UPDATE,
  API_FIN_BANK_ACCOUNT_DELETE: API_MASTER + endpoint.EP_FIN_BANK_ACCOUNT_DELETE,
  API_FIN_BANK_ACCOUNT_OB: API_MASTER + endpoint.EP_FIN_BANK_ACCOUNT_OB,

  API_FIN_BANK_BOOK_PAYMENT_LIST: API_MASTER + endpoint.EP_FIN_BANK_BOOK_PAYMENT_LIST,
  API_FIN_BANK_BOOK_PAYMENT_DETAIL: API_MASTER + endpoint.EP_FIN_BANK_BOOK_PAYMENT_DETAIL,
  API_FIN_BANK_BOOK_PAYMENT_SAVE: API_MASTER + endpoint.EP_FIN_BANK_BOOK_PAYMENT_SAVE,
  API_FIN_BANK_BOOK_PAYMENT_UPDATE: API_MASTER + endpoint.EP_FIN_BANK_BOOK_PAYMENT_UPDATE,
  API_FIN_BANK_BOOK_PAYMENT_DELETE: API_MASTER + endpoint.EP_FIN_BANK_BOOK_PAYMENT_DELETE,

  API_FIN_BANK_BOOK_RECEIPT_LIST: API_MASTER + endpoint.EP_FIN_BANK_BOOK_RECEIPT_LIST,
  API_FIN_BANK_BOOK_RECEIPT_DETAIL: API_MASTER + endpoint.EP_FIN_BANK_BOOK_RECEIPT_DETAIL,
  API_FIN_BANK_BOOK_RECEIPT_SAVE: API_MASTER + endpoint.EP_FIN_BANK_BOOK_RECEIPT_SAVE,
  API_FIN_BANK_BOOK_RECEIPT_UPDATE: API_MASTER + endpoint.EP_FIN_BANK_BOOK_RECEIPT_UPDATE,
  API_FIN_BANK_BOOK_RECEIPT_DELETE: API_MASTER + endpoint.EP_FIN_BANK_BOOK_RECEIPT_DELETE,
  API_FIN_BANK_BOOK_RECEIPT_DOCUMENT: API_MASTER + endpoint.EP_FIN_BANK_BOOK_RECEIPT_DOCUMENT,

  API_FIN_BANK_BOOK_LEDGER_LIST: API_MASTER + endpoint.EP_FIN_BANK_BOOK_LEDGER_LIST,

  API_FIN_AP_HISTORY_REPORT: API_MASTER + endpoint.EP_FIN_AP_HISTORY_REPORT,
  API_FIN_AP_TRL_BLNC_REPORT: API_MASTER + endpoint.EP_FIN_BALANCE_REPORT,
  API_FIN_BLNC_BY_COA: API_MASTER + endpoint.EP_FIN_BLNC_BY_COA_REPORT,
  API_FIN_REPORT_HIS_BY_CUST: API_MASTER + endpoint.EP_FIN_HIS_BY_CUST_REPORT,
  API_FIN_REPORT_BANK_MUT: API_MASTER + endpoint.EP_FIN_BANK_MUT_REPORT,
  API_FIN_AP_OUTSTD_BY_INV_LIST: API_MASTER + endpoint.EP_FIN_OUTSTD_BY_INV_REPORT,
  API_FIN_AP_AGING_LIST: API_MASTER + endpoint.EP_FIN_AGING_REPORT,
  API_FIN_AP_REPORT_OUTSTD_CHK_BLC_LIST: API_MASTER + endpoint.EP_FIN_OUTSTD_CHK_BLC_REPORT,
  API_FIN_AP_TRIAL_BLC_LIST: API_MASTER + endpoint.EP_FIN_AP_TRIAL_BLC_REPORT,
  API_FIN_AP_BALANCE_LIST: API_MASTER + endpoint.EP_FIN_BALANCE_REPORT,

  API_ACC_GENERAL_JOURNAL_LIST: API_MASTER + endpoint.EP_ACC_GENERAL_JOURNAL_LIST,
  API_ACC_GENERAL_JOURNAL_DETAIL: API_MASTER + endpoint.EP_ACC_GENERAL_JOURNAL_DETAIL,
  API_ACC_GENERAL_JOURNAL_SAVE: API_MASTER + endpoint.EP_ACC_GENERAL_JOURNAL_SAVE,
  API_ACC_GENERAL_JOURNAL_UPDATE: API_MASTER + endpoint.EP_ACC_GENERAL_JOURNAL_UPDATE,
  API_ACC_GENERAL_JOURNAL_DELETE: API_MASTER + endpoint.EP_ACC_GENERAL_JOURNAL_DELETE,

  API_ACC_REPORT_SUBLEDGER_LIST: API_MASTER + endpoint.EP_ACC_REPORT_SUBLEDGER_LIST,
  API_ACC_REPORT_LOST_PROFIT_LIST: API_MASTER + endpoint.EP_ACC_REPORT_LOST_PROFIT_LIST,
  API_ACC_ALL_JURNAL_LIST: API_MASTER + endpoint.EP_ACC_ALL_JURNAL_LIST,
  API_ACC_NRC_SLD_LIST: API_MASTER + endpoint.EP_ACC_NRC_SLD_LIST,
  API_ACC_REPORT_NRC_STD_LIST: API_MASTER + endpoint.EP_ACC_REPORT_NRC_STD_LIST,

  // POS
  API_POS_MENU_OUTLET_LIST: API_MASTER + endpoint.EP_POS_MENU_OUTLET_LIST,
  API_POS_MENU_OUTLET_SAVE: API_MASTER + endpoint.EP_POS_MENU_OUTLET_SAVE,
  API_POS_MENU_OUTLET_UPDATE: API_MASTER + endpoint.EP_POS_MENU_OUTLET_UPDATE,
  API_POS_MENU_OUTLET_DELETE: API_MASTER + endpoint.EP_POS_MENU_OUTLET_DELETE,

  API_POS_MENU_GROUP_LIST: API_MASTER + endpoint.EP_POS_MENU_GROUP_LIST,
  API_POS_MENU_GROUP_SAVE: API_MASTER + endpoint.EP_POS_MENU_GROUP_SAVE,
  API_POS_MENU_GROUP_UPDATE: API_MASTER + endpoint.EP_POS_MENU_GROUP_UPDATE,
  API_POS_MENU_GROUP_DELETE: API_MASTER + endpoint.EP_POS_MENU_GROUP_DELETE,

  API_POS_MENU_CATEGORY_LIST: API_MASTER + endpoint.EP_POS_MENU_CATEGORY_LIST,
  API_POS_MENU_CATEGORY_SAVE: API_MASTER + endpoint.EP_POS_MENU_CATEGORY_SAVE,
  API_POS_MENU_CATEGORY_UPDATE: API_MASTER + endpoint.EP_POS_MENU_CATEGORY_UPDATE,
  API_POS_MENU_CATEGORY_DELETE: API_MASTER + endpoint.EP_POS_MENU_CATEGORY_DELETE,

  API_POS_TENDER_MEDIA_LIST: API_MASTER + endpoint.EP_POS_TENDER_MEDIA_LIST,
  API_POS_TENDER_MEDIA_SAVE: API_MASTER + endpoint.EP_POS_TENDER_MEDIA_SAVE,
  API_POS_TENDER_MEDIA_UPDATE: API_MASTER + endpoint.EP_POS_TENDER_MEDIA_UPDATE,
  API_POS_TENDER_MEDIA_DELETE: API_MASTER + endpoint.EP_POS_TENDER_MEDIA_DELETE,

  API_POS_POINT_OF_SLS_LIST: API_MASTER + endpoint.EP_POS_POINT_OF_SALES_LIST,
  API_POS_POINT_OF_SLS_DETAIL: API_MASTER + endpoint.EP_POS_POINT_OF_SALES_DETAIL,
  API_POS_POINT_OF_SLS_SAVE: API_MASTER + endpoint.EP_POS_POINT_OF_SALES_SAVE,
  API_POS_POINT_OF_SLS_UPDATE: API_MASTER + endpoint.EP_POS_POINT_OF_SALES_UPDATE,
  API_POS_POINT_OF_SLS_DELETE: API_MASTER + endpoint.EP_POS_POINT_OF_SALES_DELETE,

  // PROFILE
  API_CHANGE_PASSWORD: API_MASTER + endpoint.EP_CHANGE_PASSWORD,
  API_CHANGE_PIN: API_MASTER + endpoint.EP_CHANGE_PIN,

  // SETUP
  API_SET_INV_OPENING_BLC_LIST: API_MASTER + endpoint.EP_SET_INV_OPENING_BLC_LIST,
  API_SET_INV_OPENING_BLC_DETAIL: API_MASTER + endpoint.EP_SET_INV_OPENING_BLC_DETAIL,
  API_SET_INV_OPENING_BLC_SAVE: API_MASTER + endpoint.EP_SET_INV_OPENING_BLC_SAVE,
  API_SET_INV_OPENING_BLC_UPDATE: API_MASTER + endpoint.EP_SET_INV_OPENING_BLC_UPDATE,
  API_SET_INV_OPENING_BLC_DELETE: API_MASTER + endpoint.EP_SET_INV_OPENING_BLC_DELETE,
  API_SET_INV_OPENING_BLC_UPLOAD: API_MASTER + endpoint.EP_SET_INV_OPENING_BLC_UPLOAD,
  API_SET_INV_OPENING_BLC_APPROVE: API_MASTER + endpoint.EP_SET_INV_OPENING_BLC_APPROVE,
  API_SET_INV_OPENING_BLC_UNAPPROVE: API_MASTER + endpoint.EP_SET_INV_OPENING_BLC_UNAPPROVE,

  API_SET_INV_OPENING_BLC_COA_LIST: API_MASTER + endpoint.EP_SET_INV_OPENING_BLC_COA_LIST,
  API_SET_INV_OPENING_BLC_COA_SAVE: API_MASTER + endpoint.EP_SET_INV_OPENING_BLC_COA_SAVE,
  // REPORTS

  API_INV_STOCK_DETAIL_QUANTITY_REPORT:
    API_MASTER_REPORT + endpoint.EP_INV_STOCK_DETAIL_QUANTITY_REPORT,
  API_INV_STOCK_DETAIL_PRICE_REPORT: API_MASTER_REPORT + endpoint.EP_INV_STOCK_DETAIL_PRICE_REPORT,
  API_INV_STOCK_DETAIL_CONSUME_REPORT:
    API_MASTER_REPORT + endpoint.EP_INV_STOCK_DETAIL_CONSUME_REPORT,
  API_INV_STOCK_OPNAME_REPORT: API_MASTER_REPORT + endpoint.EP_INV_STOCK_OPNAME_REPORT,
  API_INV_STOCK_OPNAME_TEMPLATE: API_MASTER_REPORT + endpoint.EP_INV_STOCK_OPNAME_TEMPLATE,
  API_INV_ADJUSTMENT_OUT_REPORT: API_MASTER_REPORT + endpoint.EP_INV_ADJUSTMENT_OUT_REPORT,
  API_INV_TFO_BY_LOC_REPORT: API_MASTER_REPORT + endpoint.EP_INV_TFO_BY_LOC_REPORT,

  API_ACC_SUBLEDGER_REPORT: API_MASTER_REPORT + endpoint.EP_ACC_SUBLEDGER_REPORT,
  API_ACC_NERACA_SALDO_REPORT: API_MASTER_REPORT + endpoint.EP_ACC_NERACA_SALDO_REPORT,
  API_ACC_NERACA_STANDAR_REPORT: API_MASTER_REPORT + endpoint.EP_ACC_NERACA_STANDAR_REPORT,
  API_ACC_ALL_JOURNAL_REPORT: API_MASTER_REPORT + endpoint.EP_ACC_ALL_JOURNAL_REPORT,
  API_ACC_LOST_PROFIT_REPORT: API_MASTER_REPORT + endpoint.EP_ACC_LOST_PROFIT_REPORT,

  API_PR_RCV_REPORT: API_MASTER_REPORT + endpoint.EP_PR_RCV_REPORT,

  API_FIN_OUTSTD_BY_INV_REPORT: API_MASTER_REPORT + endpoint.EP_FIN_OUTSTD_BY_INV_REPORT,
  API_FIN_OUTSTD_CHK_BLC_REPORT: API_MASTER_REPORT + endpoint.EP_FIN_OUTSTD_CHK_BLC_REPORT,
  API_FIN_AGING_REPORT: API_MASTER_REPORT + endpoint.EP_FIN_AGING_REPORT,
  API_FIN_HISTORY_REPORT: API_MASTER_REPORT + endpoint.EP_FIN_HISTORY_REPORT,
  API_FIN_BLNC_BY_COA_REPORT: API_MASTER_REPORT + endpoint.EP_FIN_BLNC_BY_COA_REPORT,
  API_FIN_BALANCE_REPORT: API_MASTER_REPORT + endpoint.EP_FIN_BALANCE_REPORT,
  API_FIN_TRIAL_BALANCE_REPORT: API_MASTER_REPORT + endpoint.EP_FIN_AP_TRIAL_BLC_REPORT,
  API_FIN_HIS_BY_CUST_REPORT: API_MASTER_REPORT + endpoint.EP_FIN_HIS_BY_CUST_REPORT,
  API_FIN_BANK_MUT_REPORT: API_MASTER_REPORT + endpoint.EP_FIN_BANK_MUT_REPORT,
  GET_DATA_POS_DATA_SALES_SAVE: API_MASTER_REPORT + endpoint.UPLOAD_CSV_FILE_POS,

  GET_DATA_JOURNAL: API_MASTER + endpoint.GET_SALES_JOURNAL,

  API_PROVINCE: endpoint.EP_PROVINCE,
  API_CITY: endpoint.EP_CITY,
  API_DISTRICT: endpoint.EP_DISTRICT,

  API_KASUS_NARKOBA_SAVE: API_MASTER + endpoint.EP_KASUS_NARKOBA_SAVE,
  API_KASUS_NARKOBA_LIST: API_MASTER + endpoint.EP_KASUS_NARKOBA_LIST,

  API_PEMBERDAYAAN_SAVE: API_MASTER + endpoint.EP_PEMBERDAYAAN_SAVE,
  API_PEMBERDAYAAN_LIST: API_MASTER + endpoint.EP_PEMBERDAYAAN_LIST,

  API_PENCEGAHAN_SAVE: API_MASTER + endpoint.EP_PENCEGAHAN_SAVE,
  API_PENCEGAHAN_LIST: API_MASTER + endpoint.EP_PENCEGAHAN_LIST,
}

export const RETAIL = () =>
  Config.APPSCHEMA === 'TRUBUS' ||
  Config.APPSCHEMA === 'ANDHIKA' ||
  Config.APPSCHEMA === 'PPG' ||
  Config.APPSCHEMA === 'TRUBUSTESTER'

export const RESTAURANT = () =>
  Config.APPSCHEMA === 'ZENBU' ||
  Config.APPSCHEMA === 'BSTEAK_CENTRAL' ||
  Config.APPSCHEMA === 'TEKO'

export default Config
