const actions = {
  SET_STATE: 'setInvOpeningBalance/SET_STATE',
  HANDLE_STATE: 'setInvOpeningBalance/HANDLE_STATE',
  HANDLE_CONTENT: 'setInvOpeningBalance/HANDLE_CONTENT',
  GET_DATA_INV_OPENING_BLC_LIST: 'setInvOpeningBalance/GET_DATA_INV_OPENING_BLC_LIST',
  GET_DATA_INV_OPENING_BLC_DETAIL: 'setInvOpeningBalance/GET_DATA_INV_OPENING_BLC_DETAIL',
  GET_DATA_INV_OPENING_BLC_SAVE: 'setInvOpeningBalance/GET_DATA_INV_OPENING_BLC_SAVE',
  GET_DATA_INV_OPENING_BLC_UPDATE: 'setInvOpeningBalance/GET_DATA_INV_OPENING_BLC_UPDATE',
  GET_DATA_INV_OPENING_BLC_DELETE: 'setInvOpeningBalance/GET_DATA_INV_OPENING_BLC_DELETE',
  GET_DATA_INV_OPENING_BLC_APPROVE: 'setInvOpeningBalance/GET_DATA_INV_OPENING_BLC_APPROVE',
  GET_DATA_INV_OPENING_BLC_UNAPPROVE: 'setInvOpeningBalance/GET_DATA_INV_OPENING_BLC_UNAPPROVE',
  GET_DATA_INV_OPENING_BLC_IMPORT: 'setInvOpeningBalance/GET_DATA_INV_OPENING_BLC_IMPORT',
}

export default actions
