const actions = {
  SET_STATE: 'user/SET_STATE',
  LOGIN: 'user/LOGIN',
  LOGOUT: 'user/LOGOUT',
  FORGOT: 'user/FORGOT',
  REGISTER: 'user/REGISTER',
  CHECK_TOKEN: 'user/CHECK_TOKEN',
  RESET_PASSWORD: 'user/RESET_PASSWORD',
  CHANGE_COMPANY: 'user/CHANGE_COMPANY',
  GET_OUTLET: 'user/GET_OUTLET',
  GET_COMPANY: 'user/GET_COMPANY',
  GET_MST_COMPANY: 'user/GET_MST_COMPANY',
  USER_CHANGE_PASSWORD: 'user/USER_CHANGE_PASSWORD',
  USER_CHANGE_PIN: 'user/USER_CHANGE_PIN',
  LOAD_CURRENT_ACCOUNT: 'user/LOAD_CURRENT_ACCOUNT',
}

export default actions
