const actions = {
  SET_STATE: 'setInvOpeningCOA/SET_STATE',
  HANDLE_STATE: 'setInvOpeningCOA/HANDLE_STATE',
  HANDLE_CONTENT: 'setInvOpeningCOA/HANDLE_CONTENT',
  GET_DATA_INV_OPENING_COA_LIST: 'setInvOpeningCOA/GET_DATA_INV_OPENING_COA_LIST',
  GET_DATA_INV_OPENING_COA_SAVE: 'setInvOpeningCOA/GET_DATA_INV_OPENING_COA_SAVE',
  GET_DATA_INV_OPENING_COA_IMPORT: 'setInvOpeningCOA/GET_DATA_INV_OPENING_COA_IMPORT',
}

export default actions
